### ISSUE TITLE
Does not work behind proxy

### ISSUE THREAD

**Issue by gentisaliu** [jstayton/GoogleMapsGeocoder#16]
It would be nice to have an option or parameter to pass in proxy parameters.

**Comment by jstayton** [comment]
Hey @gentisaliu,

Thanks for the feedback! Can you provide an example of how you might expect it to work? Do you simply mean being able to specify a different URL to make the request against?

**Comment by gentisaliu** [comment]
Hi @jstayton,

No, the request URL should remain the same - PHP can handle proxies by itself, see [SO answer]http://stackoverflow.com/a/1336419/277106()

I forked your repository and added this functionality myself, see this commit: https://github.com/gentisaliu/GoogleMapsGeocoder/commit/bcda4509659593171f2b335d4453ea96c5c8aeff

The proxy options are configured using setters: `setHttpProxy`, `setHttpsProxy`, `setProxyUser`, `setProxyPassword`.

I wanted to do a PR, but I still haven't gotten around to test it. Thanks!

**Comment by jstayton** [comment]
Cool, now that there's a PR, let's move the discussion there: #17.
