### ISSUE TITLE
Simplify lookup of city/state etc... 

### ISSUE THREAD

**Issue by stratease** [jstayton/GoogleMapsGeocoder#19]
Would having some helper methods/classes to simplify normalizing the locality and administrative values into a simplified getCity() getState() sort of syntax for the results returned fall into scope in this repo? 

Would you be willing to see a forked version of this? thanks...

**Comment by jstayton** [comment]
Hey @stratease,

Not at this point. If and when a new major version of this library is considered, maybe then. But I don't have any plans for `v3` at this time.
