### ISSUE TITLE
Seems not worked after update the Google Maps API plans.

### ISSUE THREAD

**Issue by vrusua** [jstayton/GoogleMapsGeocoder#22]
Hi Justin,

thank you for the great tool! However, it seems not worked for me, I suppose after update the Google Maps API plans, see http://googlegeodevelopers.blogspot.gr/2016/06/building-for-scale-updates-to-google.html

Can you check, is the query url works well?

Thank you.

Cheers,
Ruslan

**Comment by jstayton** [comment]
Hi Ruslan,

Are you setting an API key? Based on the post you linked, it appears that's required now.

**Comment by vrusua** [comment]
Hi Justin,

sure, I use the new API key, but the script is not working. This is not the
old business api key. Google uses now api keys per project domain and per
each service. Thank you.

суббота, 2 июля 2016 г. пользователь Justin Stayton написал:

> Hi Ruslan,
>
> Are you setting an API key? Based on the post you linked, it appears
> that's required now.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jstayton/GoogleMapsGeocoder/issues/22#issuecomment-230055545>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AB-i5bXqL-kMaoXOkzhyzZsEYMhmXDimks5qRYwmgaJpZM4JCWlh>
> .
>


-- 
Sent from iPhone

**Comment by vrusua** [comment]
Hi Justin,


just to specify this. Once I use the API key, I got the error:

{ "error_message" : "Browser API keys cannot have referer restrictions when used with this API.", "results" : [], "status" : "REQUEST_DENIED" }

However, all works well on domains created before the 22nd of June without setting up the API key.
But I must apply the API key on new domains.

Thank you.

Cheers,
Ruslan

**Comment by vrusua** [comment]
Hi Justin,

I just created the server type Google Maps API key instead the browser one, and all works well now.
Sorry to disturb you and my apologies for the false issue, it can be closed now.

Thank you.

Cheers
Ruslan

**Comment by jstayton** [comment]
No worries. Glad you got it figured out!
