### ISSUE TITLE
geocode not responding properly

### ISSUE THREAD

**Issue by rrpatil761** [jstayton/GoogleMapsGeocoder#23]
I have a script that collects 1000 of addresses from DB and gets related lat and lng and updates back into DB.

As there is a loop to get geocode it is not responding randomly venues as it is the asynchronous call.

Please help me to make it as sync so that all venues get processed without such interruption.

**Comment by jstayton** [comment]
@rrpatil761 I'm very sorry for never responding to you here. As my silence likely hinted, I stopped maintaining this project long ago. I'm now officially deprecating it to make that clear.

If you'd like to continue supporting a forked version, please reach out on Twitter ([@kidjustino](https://twitter.com/kidjustino)) to have it listed in the README.
