### ISSUE TITLE
Will fail when allow_url_fopen = Off

### ISSUE THREAD

**Issue by swimson** [jstayton/GoogleMapsGeocoder#24]
Heads up, when allow_url_fopen = Off then this library will fail because file_get_contents() will only work for local files.

I'm going to be writing a patch so this library works with cURL as well as file_get_contents, are you interested in a PR with the updated code?

**Comment by jstayton** [comment]
@swimson I'm very sorry for never responding to you here. As my silence likely hinted, I stopped maintaining this project long ago. I'm now officially deprecating it to make that clear.

If you'd like to continue supporting a forked version, please reach out on Twitter ([@kidjustino](https://twitter.com/kidjustino)) to have it listed in the README.
