### ISSUE TITLE
Any example how I can save the JSON output format into a MySQL database?

### ISSUE THREAD

**Issue by kirbyfern** [jstayton/GoogleMapsGeocoder#27]
Btw awesome wrapper for google geocoding.
- Is there any specific example how I can use this to save a JSON format output to a MySQL database?
- It would validate that a user's input address is valid if not outputs an error to the page.

**Comment by jstayton** [comment]
@kirbygit I'm very sorry for never responding to you here. As my silence likely hinted, I stopped maintaining this project long ago. I'm now officially deprecating it to make that clear.

If you'd like to continue supporting a forked version, please reach out on Twitter ([@kidjustino](https://twitter.com/kidjustino)) to have it listed in the README.
